packages:
  device: !include device/device.yaml
  sensors: !include device/sensors.yaml
  lvgl: !include device/lvgl.yaml
  backlight: !include addon/backlight.yaml
  time: !include addon/time.yaml
  network: !include addon/network.yaml
  fonts: !include assets/fonts.yaml
  icons: !include assets/icons.yaml
  button: !include theme/button.yaml
  weather: !include addon/weather.yaml
  sleep_wake: !include addon/sleep_wake.yaml

substitutions:
  ceiling_fan: fan.guest_bedroom_left_ceilng_fan 
  yellow_light: light.guest_bedroom_left_ceiling_light_yellow   # must match ha_yellow_light.yaml
  white_light: light.guest_bedroom_left_ceiling_light_white   # must match ha_white_light.yaml
