substitutions:
  ceiling_fan: fan.office_ceiling_fan      # must match ha_fan.yaml
  yellow_light: light.office_ceiling_light_yellow   # must match ha_yellow_light.yaml
  white_light: light.office_ceiling_light_white   # must match ha_white_light.yaml
# ─── Home Assistant sensors ───────────────────────────────
binary_sensor:
  - platform: homeassistant
    id: ha_fan_state
    entity_id: ${ceiling_fan}          # ← change to your fan entity
    on_state:
      - lambda: id(fan_on) = x;
      - if:
          condition:
            lambda: return x;
          then:
            # Fan turned ON – blue icon + "Running" label
            - lvgl.widget.update:
                id: fan_icon_lbl
                text_color: 0x29B6F6

            - lvgl.widget.update:
                id: fan_btn_toggle
                bg_color: ${color_btn_on}
          else:
            # Fan turned OFF – grey icon + "Off" label, reset angle
            - globals.set:
                id: fan_angle
                value: "0"
            - lvgl.widget.update:
                id: fan_icon_lbl
                text_color: 0x546E7A
                transform_angle: 0
            - lvgl.widget.update:
                id: fan_btn_toggle
                bg_color: ${color_btn_off}

  - platform: homeassistant
    id: y_light_state
    entity_id: ${yellow_light}          # ← change to your light entity
    on_state:
      #- lambda: id(y_light_on) = x;
      - if:
          condition:
            lambda: |-
              if (!id(y_light_state).has_state()) return false;
              return x;
          then:
            # Light turned ON – yellow icon + "On" label
            - lvgl.widget.update:
                id: y_light_icon_lbl
                text_color: 0xFFEE58
            - lvgl.widget.update:
                id: y_light_btn_toggle
                bg_color: ${color_btn_yellow}
          else:
            # Light turned OFF – grey icon + "Off" label
            - lvgl.widget.update:
                id: y_light_icon_lbl
                text_color: 0x546E7A
            - lvgl.widget.update:
                id: y_light_btn_toggle
                bg_color: ${color_btn_off}
    name: "Yellow Light State"

  - platform: homeassistant
    id: w_light_state
    entity_id: ${white_light}          # ← change to your light entity
    on_state:
      #- lambda: id(w_light_on) = x;
      - if:
          condition:
            lambda: |-
              if (!id(y_light_state).has_state()) return false;
              return x;
          then:
            # Light turned ON – yellow icon + "On" label
            - lvgl.widget.update:
                id: w_light_icon_lbl
                text_color: 0xeeeeee
            - lvgl.widget.update:
                id: w_light_btn_toggle
                bg_color: ${color_btn_white}
          else:
            # Light turned OFF – grey icon + "Off" label
            - lvgl.widget.update:
                id: w_light_icon_lbl
                text_color: 0x546E7A
            - lvgl.widget.update:
                id: w_light_btn_toggle
                bg_color: ${color_btn_off}
    name: "White Light State"
 
sensor:
  - platform: homeassistant
    id: ha_fan_speed
    entity_id: ${ceiling_fan}          # ← same entity
    attribute: percentage
    on_value:
      then:
        - lvgl.slider.update:
            id: fan_speed_slider
            value: !lambda 'return x;'
        - lvgl.label.update:
            id: fan_speed_label
            text: !lambda |-
              if (isnan(x)) return std::string("--");
              return std::to_string((int)x) + "%";

  - platform: homeassistant
    id: y_light_brigfhtness
    entity_id: ${yellow_light}          # ← same entity as in ha_yellow_light
    attribute: brightness
    on_value:
      then:
        - lvgl.slider.update:
            id: y_light_brightness_slider
            value: !lambda |- 
              if(isnan(x)) return 0;
              return x;   
        - lvgl.label.update:
            id: y_light_brightness_label
            text: !lambda |-
              if (isnan(x)) return std::string("--");
              return std::to_string((int)x) + "%";

  - platform: homeassistant
    id: w_light_brigfhtness
    entity_id: ${white_light}          # ← same entity as in ha_white_light
    attribute: brightness
    on_value:
      then:
        - lvgl.slider.update:
            id: w_light_brightness_slider
            value: !lambda |- 
              if(isnan(x)) return 0;
              return x;   
        - lvgl.label.update:
            id: w_light_brightness_label
            text: !lambda |-
              if (isnan(x)) return std::string("--");
              return std::to_string((int)x) + "%";