substitutions:
  ceiling_fan: fan.office_ceiling_fan      # must match ha_fan.yaml

# ─── Home Assistant sensors ───────────────────────────────
binary_sensor:
  - platform: homeassistant
    id: ha_fan_state
    entity_id: ${ceiling_fan}          # ← change to your fan entity
    on_state:
      - lambda: id(fan_on) = x;
      - if:
          condition:
            lambda: return x;
          then:
            # Fan turned ON – blue icon + "Running" label
            - lvgl.widget.update:
                id: fan_icon_lbl
                text_color: 0x29B6F6

            - lvgl.widget.update:
                id: fan_btn_toggle
                bg_color: ${color_btn_on}
            # fan toggle lable to on    
            - lvgl.label.update:
                id: fan_btn_state_lbl
                text: "  fan On"
          else:
            # Fan turned OFF – grey icon + "Off" label, reset angle
            - globals.set:
                id: fan_angle
                value: "0"
            - lvgl.widget.update:
                id: fan_icon_lbl
                text_color: 0x546E7A
                transform_angle: 0
            - lvgl.widget.update:
                id: fan_btn_toggle
                bg_color: ${color_btn_off}
            - lvgl.label.update:
                id: fan_btn_state_lbl
                text: "  Fan Off"
            - lvgl.slider.update:
                id: fan_speed_slider
                value: !lambda 'return x;'
            - lvgl.label.update:
                id: fan_speed_label
                text: !lambda |-
                  if (isnan(x)) return std::string("--");
                  return std::to_string((int)x) + "%";
            
sensor:
  - platform: homeassistant
    id: ha_fan_speed
    entity_id: ${ceiling_fan}          # ← same entity
    attribute: percentage
    on_value:
      then:
        - lvgl.slider.update:
            id: fan_speed_slider
            value: !lambda 'return x;'
        - lvgl.label.update:
            id: fan_speed_label
            text: !lambda |-
              if (isnan(x)) return std::string("--");
              return std::to_string((int)x) + "%";

   